services:

  opensearch_search_relevance:
    build: .
    container_name: opensearch_search_relevance
    environment:
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: "true"
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
      http.max_content_length: 500mb
      OPENSEARCH_JAVA_OPTS: "-Xms16g -Xmx16g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
